// Code generated by bpf2go; DO NOT EDIT.

package ebpfutil

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadAgentSelector returns the embedded CollectionSpec for AgentSelector.
func LoadAgentSelector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentSelectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load AgentSelector: %w", err)
	}

	return spec, err
}

// LoadAgentSelectorObjects loads AgentSelector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentSelectorObjects
//	*AgentSelectorPrograms
//	*AgentSelectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentSelectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgentSelector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentSelectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentSelectorSpecs struct {
	AgentSelectorProgramSpecs
	AgentSelectorMapSpecs
}

// AgentSelectorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentSelectorProgramSpecs struct {
	AgentUdpSelector *ebpf.ProgramSpec `ebpf:"agent_udp_selector"`
}

// AgentSelectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentSelectorMapSpecs struct {
	PebbleUdpTargets *ebpf.MapSpec `ebpf:"pebble_udp_targets"`
}

// AgentSelectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentSelectorObjects struct {
	AgentSelectorPrograms
	AgentSelectorMaps
}

func (o *AgentSelectorObjects) Close() error {
	return _AgentSelectorClose(
		&o.AgentSelectorPrograms,
		&o.AgentSelectorMaps,
	)
}

// AgentSelectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentSelectorMaps struct {
	PebbleUdpTargets *ebpf.Map `ebpf:"pebble_udp_targets"`
}

func (m *AgentSelectorMaps) Close() error {
	return _AgentSelectorClose(
		m.PebbleUdpTargets,
	)
}

// AgentSelectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentSelectorPrograms struct {
	AgentUdpSelector *ebpf.Program `ebpf:"agent_udp_selector"`
}

func (p *AgentSelectorPrograms) Close() error {
	return _AgentSelectorClose(
		p.AgentUdpSelector,
	)
}

func _AgentSelectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agentselector_bpf.o
var _AgentSelectorBytes []byte
