// Code generated by bpf2go; DO NOT EDIT.

package ebpfutil

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type HashSelectorHashState struct {
	Active uint32
	Pad    uint32
}

// LoadHashSelector returns the embedded CollectionSpec for HashSelector.
func LoadHashSelector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HashSelectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load HashSelector: %w", err)
	}

	return spec, err
}

// LoadHashSelectorObjects loads HashSelector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*HashSelectorObjects
//	*HashSelectorPrograms
//	*HashSelectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadHashSelectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadHashSelector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// HashSelectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HashSelectorSpecs struct {
	HashSelectorProgramSpecs
	HashSelectorMapSpecs
}

// HashSelectorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HashSelectorProgramSpecs struct {
	HashUdpSelector *ebpf.ProgramSpec `ebpf:"hash_udp_selector"`
}

// HashSelectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HashSelectorMapSpecs struct {
	PebbleHashState  *ebpf.MapSpec `ebpf:"pebble_hash_state"`
	PebbleUdpTargets *ebpf.MapSpec `ebpf:"pebble_udp_targets"`
}

// HashSelectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadHashSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type HashSelectorObjects struct {
	HashSelectorPrograms
	HashSelectorMaps
}

func (o *HashSelectorObjects) Close() error {
	return _HashSelectorClose(
		&o.HashSelectorPrograms,
		&o.HashSelectorMaps,
	)
}

// HashSelectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadHashSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type HashSelectorMaps struct {
	PebbleHashState  *ebpf.Map `ebpf:"pebble_hash_state"`
	PebbleUdpTargets *ebpf.Map `ebpf:"pebble_udp_targets"`
}

func (m *HashSelectorMaps) Close() error {
	return _HashSelectorClose(
		m.PebbleHashState,
		m.PebbleUdpTargets,
	)
}

// HashSelectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadHashSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type HashSelectorPrograms struct {
	HashUdpSelector *ebpf.Program `ebpf:"hash_udp_selector"`
}

func (p *HashSelectorPrograms) Close() error {
	return _HashSelectorClose(
		p.HashUdpSelector,
	)
}

func _HashSelectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hashselector_bpf.o
var _HashSelectorBytes []byte
