// Code generated by bpf2go; DO NOT EDIT.

package ebpfutil

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type RrSelectorRrState struct {
	Counter uint32
	Active  uint32
}

// LoadRrSelector returns the embedded CollectionSpec for RrSelector.
func LoadRrSelector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RrSelectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load RrSelector: %w", err)
	}

	return spec, err
}

// LoadRrSelectorObjects loads RrSelector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RrSelectorObjects
//	*RrSelectorPrograms
//	*RrSelectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRrSelectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRrSelector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RrSelectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RrSelectorSpecs struct {
	RrSelectorProgramSpecs
	RrSelectorMapSpecs
}

// RrSelectorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RrSelectorProgramSpecs struct {
	RrUdpSelector *ebpf.ProgramSpec `ebpf:"rr_udp_selector"`
}

// RrSelectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RrSelectorMapSpecs struct {
	PebbleRrState    *ebpf.MapSpec `ebpf:"pebble_rr_state"`
	PebbleUdpTargets *ebpf.MapSpec `ebpf:"pebble_udp_targets"`
}

// RrSelectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRrSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type RrSelectorObjects struct {
	RrSelectorPrograms
	RrSelectorMaps
}

func (o *RrSelectorObjects) Close() error {
	return _RrSelectorClose(
		&o.RrSelectorPrograms,
		&o.RrSelectorMaps,
	)
}

// RrSelectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRrSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type RrSelectorMaps struct {
	PebbleRrState    *ebpf.Map `ebpf:"pebble_rr_state"`
	PebbleUdpTargets *ebpf.Map `ebpf:"pebble_udp_targets"`
}

func (m *RrSelectorMaps) Close() error {
	return _RrSelectorClose(
		m.PebbleRrState,
		m.PebbleUdpTargets,
	)
}

// RrSelectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRrSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type RrSelectorPrograms struct {
	RrUdpSelector *ebpf.Program `ebpf:"rr_udp_selector"`
}

func (p *RrSelectorPrograms) Close() error {
	return _RrSelectorClose(
		p.RrUdpSelector,
	)
}

func _RrSelectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rrselector_bpf_nolock_bpf.o
var _RrSelectorBytes []byte
