// Code generated by bpf2go; DO NOT EDIT.

package ebpfutil

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ScanSplitSelectorSplitState struct {
	Active      uint32
	ScanCounter uint32
	GetCounter  uint32
	Pad         uint32
}

// LoadScanSplitSelector returns the embedded CollectionSpec for ScanSplitSelector.
func LoadScanSplitSelector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ScanSplitSelectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ScanSplitSelector: %w", err)
	}

	return spec, err
}

// LoadScanSplitSelectorObjects loads ScanSplitSelector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ScanSplitSelectorObjects
//	*ScanSplitSelectorPrograms
//	*ScanSplitSelectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadScanSplitSelectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadScanSplitSelector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ScanSplitSelectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScanSplitSelectorSpecs struct {
	ScanSplitSelectorProgramSpecs
	ScanSplitSelectorMapSpecs
}

// ScanSplitSelectorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScanSplitSelectorProgramSpecs struct {
	SplitUdpSelector *ebpf.ProgramSpec `ebpf:"split_udp_selector"`
}

// ScanSplitSelectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ScanSplitSelectorMapSpecs struct {
	PebbleSplitState *ebpf.MapSpec `ebpf:"pebble_split_state"`
	PebbleUdpTargets *ebpf.MapSpec `ebpf:"pebble_udp_targets"`
}

// ScanSplitSelectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadScanSplitSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScanSplitSelectorObjects struct {
	ScanSplitSelectorPrograms
	ScanSplitSelectorMaps
}

func (o *ScanSplitSelectorObjects) Close() error {
	return _ScanSplitSelectorClose(
		&o.ScanSplitSelectorPrograms,
		&o.ScanSplitSelectorMaps,
	)
}

// ScanSplitSelectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadScanSplitSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScanSplitSelectorMaps struct {
	PebbleSplitState *ebpf.Map `ebpf:"pebble_split_state"`
	PebbleUdpTargets *ebpf.Map `ebpf:"pebble_udp_targets"`
}

func (m *ScanSplitSelectorMaps) Close() error {
	return _ScanSplitSelectorClose(
		m.PebbleSplitState,
		m.PebbleUdpTargets,
	)
}

// ScanSplitSelectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadScanSplitSelectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ScanSplitSelectorPrograms struct {
	SplitUdpSelector *ebpf.Program `ebpf:"split_udp_selector"`
}

func (p *ScanSplitSelectorPrograms) Close() error {
	return _ScanSplitSelectorClose(
		p.SplitUdpSelector,
	)
}

func _ScanSplitSelectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed scansplitselector_bpf.o
var _ScanSplitSelectorBytes []byte
