//go:build ignore

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/udp.h>
#include <linux/in.h>

struct {
	__uint(type, BPF_MAP_TYPE_REUSEPORT_SOCKARRAY);
	__uint(max_entries, 128);
	__type(key, __u32);
	__type(value, __u32);
	__uint(pinning, LIBBPF_PIN_BY_NAME);
} pebble_udp_targets SEC(".maps");

// EVOLVE-BLOCK-START

/*
 * Design:
 * -------
 * The primary latency problem is queueing: rare, long SCANs (~2 ms) share
 * per-socket UDP receive queues with very short GETs (~10 µs). With a
 * stateless random selector, each worker behaves like an M/G/1 queue that
 * mixes both request types, so occasional SCANs cause head-of-line blocking
 * for many queued GETs, inflating end-to-end p99 latency.
 *
 * Goals:
 *   - Steer SCANs away from GETs to avoid mixed queues.
 *   - Keep workers reasonably utilized without extra maps or config.
 *   - Remain verifier-friendly: O(1) per packet, no loops, minimal state.
 *
 * Approach:
 *   - Use the existing pebble_agent_state map to learn the number of active
 *     reuseport workers (Active).
 *   - Statistically partition the reuseport sockarray indices into two lanes:
 *
 *       * SCAN lane: indices [0, scan_cnt-1]
 *       * GET lane:  indices [scan_cnt, Active-1]
 *
 *     with scan_cnt sized as:
 *       * Active == 1:   scan_cnt = 1 (single mixed worker).
 *       * Active == 2/3: scan_cnt = 1 (one SCAN worker, at least one GET).
 *       * Active >= 4:   scan_cnt = Active / 2 (about half workers for SCANs).
 *
 *   - Parse L2+L3+L4 headers from sk_reuseport_md::{data,data_end}:
 *       Ethernet → IPv4 → UDP → payload.
 *   - Classify a packet as SCAN iff the UDP payload starts with "SCAN "
 *     or "SCAN\t". Everything else is treated as GET/other.
 *   - Only apply lane partitioning when classification is valid; otherwise,
 *     fall back to using all workers uniformly. This prevents accidental
 *     capacity loss if parsing fails (e.g., non-Ethernet/IPv6).
 *   - Within the chosen lane, pick a worker index using bpf_get_prandom_u32().
 *   - Call bpf_sk_select_reuseport once with that slot.
 *
 * This isolates GETs from SCANs' long service times, keeps total worker
 * capacity roughly matched to their CPU shares, and remains fully stateless
 * and verifier-friendly.
 */

struct agent_state {
	__u32 active;
	__u32 pad;
};

struct {
	__uint(type, BPF_MAP_TYPE_ARRAY);
	__uint(max_entries, 1);
	__type(key, __u32);
	__type(value, struct agent_state);
	__uint(pinning, LIBBPF_PIN_BY_NAME);
} pebble_agent_state SEC(".maps");

SEC("sk_reuseport/selector")
enum sk_action agent_udp_selector(struct sk_reuseport_md *reuse)
{
	__u32 key = 0;
	struct agent_state *state;
	__u32 active;
	int is_scan = 0;
	int classification_valid = 0;

	void *data;
	void *data_end;
	struct ethhdr *eth;
	struct iphdr *iph;
	void *l4;
	struct udphdr *uh;
	__u8 *udp_payload;
	__u32 ihl;

	__u32 lane_start;
	__u32 lane_size;
	__u32 rnd;
	__u32 idx;
	__u32 slot;
	__u32 scan_cnt;
	__u32 get_cnt;

	state = bpf_map_lookup_elem(&pebble_agent_state, &key);
	if (!state)
		return SK_PASS;

	active = state->active;
	if (active == 0)
		return SK_PASS;

	/* Safety: never index beyond the sockarray size even if misconfigured. */
	if (active > 128)
		active = 128;

	/*
	 * Classify packet as SCAN vs non-SCAN by peeking into the UDP payload.
	 * We assume Ethernet + IPv4 + UDP as generated by the workload client.
	 * All accesses are guarded by data_end checks for verifier safety.
	 */
	data = (void *)(long)reuse->data;
	data_end = (void *)(long)reuse->data_end;

	/* Parse Ethernet header. */
	eth = data;
	if ((void *)(eth + 1) > data_end)
		goto classify_done;

	if (bpf_ntohs(eth->h_proto) != ETH_P_IP)
		goto classify_done;

	/* Parse IPv4 header. */
	iph = (void *)(eth + 1);
	if ((void *)(iph + 1) > data_end)
		goto classify_done;

	if (iph->protocol != IPPROTO_UDP)
		goto classify_done;

	ihl = iph->ihl;
	if (ihl < 5 || ihl > 15)
		goto classify_done;

	l4 = (void *)((__u8 *)iph + ihl * 4);
	uh = (struct udphdr *)l4;
	if ((void *)(uh + 1) > data_end)
		goto classify_done;

	/* UDP payload starts after UDP header. */
	udp_payload = (__u8 *)(uh + 1);

	/* Need at least 1 byte to check for leading 'S'. */
	if ((void *)(udp_payload + 1) > data_end)
		goto classify_done;

	classification_valid = 1;

	if (udp_payload[0] == 'S') {
		/* Need full "SCAN " / "SCAN\t" (5 bytes) to classify as SCAN. */
		if ((void *)(udp_payload + 5) <= data_end &&
		    udp_payload[1] == 'C' &&
		    udp_payload[2] == 'A' &&
		    udp_payload[3] == 'N' &&
		    (udp_payload[4] == ' ' || udp_payload[4] == '\t')) {
			is_scan = 1;
		}
	}

classify_done:
	/*
	 * Lane selection:
	 *  - If only one worker is active, everyone goes to slot 0.
	 *  - If more than one worker:
	 *      * When classification failed, fall back to using all workers.
	 *      * When classification succeeded:
	 *          - SCANs  → slots [0, scan_cnt-1]   (SCAN lane).
	 *          - others → slots [scan_cnt, active-1] (GET lane).
	 */
	lane_start = 0;
	lane_size  = active;

	if (active > 1) {
		if (!classification_valid) {
			/* Parsing failed: use all workers uniformly. */
			lane_start = 0;
			lane_size  = active;
		} else {
			/* Allocate workers to SCAN lane. */
			if (active >= 4)
				scan_cnt = active / 2;  /* e.g., 6 -> 3 SCAN workers */
			else
				scan_cnt = 1;           /* active == 2 or 3 */

			get_cnt = active - scan_cnt;
			if (get_cnt == 0) {
				/* Safety: always keep at least one GET worker. */
				scan_cnt = active - 1;
				get_cnt = 1;
			}

			if (is_scan) {
				lane_start = 0;
				lane_size  = scan_cnt;
			} else {
				lane_start = scan_cnt;
				lane_size  = get_cnt;
			}
		}
	}

	if (lane_size == 0)
		return SK_PASS;

	rnd = bpf_get_prandom_u32();
	idx = rnd % lane_size;
	slot = lane_start + idx;

	/* Single reuseport selection; kernel ignores any additional calls. */
	bpf_sk_select_reuseport(reuse, &pebble_udp_targets, &slot, 0);

	return SK_PASS;
}

// EVOLVE-BLOCK-END

char _license[] SEC("license") = "GPL";