#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export GOCACHE="${GOCACHE:-$ROOT/.gocache}"

THREADS=${THREADS:-6}
POLICY=${POLICY:-agent}
DURATION=${DURATION:-10}
RATE=${RATE:-45000}
GET_FRAC=${GET_FRAC:-.995}
SCAN_LIMIT=${SCAN_LIMIT:-1500}
SEND_WORKERS=${SEND_WORKERS:-6}
LISTEN=${LISTEN:-127.0.0.1:9000}
GET_DELAY=${GET_DELAY:-10us}
SCAN_DELAY=${SCAN_DELAY:-2ms}
ITERATIONS=${ITERATIONS:-3}
WARMUP_DURATION=${WARMUP_DURATION:-0}
OUTPUT_ROOT=${OUTPUT_ROOT:-$ROOT/results}
RUN_ID_OVERRIDE=${RUN_ID:-}
RUN_STATE_DIR_OVERRIDE=${RUN_STATE_DIR:-}
SERVER_CORES=${SERVER_CORES:-}
CLIENT_CORES=${CLIENT_CORES:-}
CPUSET_POOL=${CPUSET_POOL:-}
TASKSET_BIN=${TASKSET_BIN:-taskset}

join_by() {
  local sep="$1"
  shift || true
  local IFS="$sep"
  echo "$*"
}

expand_cpu_list() {
  local input="${1//[[:space:]]/}"
  local token start end cpu
  local IFS=',' parts
  IFS=',' read -ra parts <<< "$input"
  for token in "${parts[@]}"; do
    [[ -z "$token" ]] && continue
    if [[ "$token" =~ ^([0-9]+)-([0-9]+)$ ]]; then
      start=${BASH_REMATCH[1]}
      end=${BASH_REMATCH[2]}
      if (( start > end )); then
        echo "Invalid CPU range $token" >&2
        return 1
      fi
      for ((cpu = start; cpu <= end; cpu++)); do
        printf '%s\n' "$cpu"
      done
    elif [[ "$token" =~ ^[0-9]+$ ]]; then
      printf '%s\n' "$token"
    else
      echo "Invalid CPU token '$token'" >&2
      return 1
    fi
  done
}

ensure_positive_int() {
  local name="$1"
  local value="$2"
  if [[ ! "$value" =~ ^[1-9][0-9]*$ ]]; then
    echo "$name must be a positive integer (got '$value')" >&2
    exit 1
  fi
}

resolve_cpu_pool() {
  local source="$1"
  local path="/sys/devices/system/node/node0/cpulist"
  if [[ ! -r "$path" ]]; then
    echo "Unable to read NUMA node 0 CPU list from $path" >&2
    exit 1
  fi
  local node0_raw
  node0_raw=$(tr -d '[:space:]' < "$path")
  local -a NODE0_CPUS=()
  mapfile -t NODE0_CPUS < <(expand_cpu_list "$node0_raw") || {
    echo "Failed to parse NUMA node 0 CPU list '$node0_raw'" >&2
    exit 1
  }

  local cpulist
  if [[ -n "$source" ]]; then
    cpulist="${source//[[:space:]]/}"
  else
    cpulist="$node0_raw"
  fi
  if [[ -z "$cpulist" ]]; then
    echo "Resolved CPU pool is empty" >&2
    exit 1
  fi

  mapfile -t AVAILABLE_CPUS < <(expand_cpu_list "$cpulist") || {
    echo "Failed to parse CPU list '$cpulist'" >&2
    exit 1
  }
  if (( ${#AVAILABLE_CPUS[@]} == 0 )); then
    echo "Resolved CPU pool contains no CPUs" >&2
    exit 1
  fi

  local -A NODE0_LOOKUP=()
  local cpu
  for cpu in "${NODE0_CPUS[@]}"; do
    NODE0_LOOKUP["$cpu"]=1
  done
  for cpu in "${AVAILABLE_CPUS[@]}"; do
    if [[ -z "${NODE0_LOOKUP[$cpu]:-}" ]]; then
      echo "CPU $cpu is not part of NUMA node 0 (allowed: $node0_raw)" >&2
      exit 1
    fi
  done
}

ensure_taskset_available() {
  if ! command -v "$TASKSET_BIN" >/dev/null 2>&1; then
    echo "Required cpu pinning tool '$TASKSET_BIN' not found in PATH" >&2
    exit 1
  fi
}

usage() {
  cat <<USAGE
Usage: $0 [options]
  --threads <n>       worker sockets (default: $THREADS)
  --policy <name>     default|round_robin|agent|scan_split (default: $POLICY)
  --duration <sec>    workload duration seconds (default: $DURATION)
  --rate <rps>        send rate (default: $RATE)
  --get-frac <f>      GET fraction (default: $GET_FRAC)
  --scan-limit <n>    SCAN limit (default: $SCAN_LIMIT)
  --listen <addr>     UDP listen address (default: $LISTEN)
  --get-delay <dur>   synthetic GET latency (e.g. 10us; passed to server)
  --scan-delay <dur>  synthetic SCAN latency (e.g. 2ms; passed to server)
  --send-workers <n>  concurrent client send goroutines (default: $SEND_WORKERS)
  --iterations <n>    number of workload iterations (default: $ITERATIONS)
  --output-dir <path> directory where run artifacts are written (default: $OUTPUT_ROOT)
  --run-id <id>       override autogenerated run identifier
  --state-dir <path>  directory for server pid/temporary state
  --server-cores <n>  number of dedicated NUMA node 0 cores for the server
  --client-cores <n>  number of dedicated NUMA node 0 cores for the client
USAGE
}

OPTS=$(getopt -o '' \
  --long threads:,policy:,duration:,rate:,get-frac:,scan-limit:,listen:,get-delay:,scan-delay:,send-workers:,iterations:,output-dir:,run-id:,state-dir:,server-cores:,client-cores:,help \
  -n 'run.sh' -- "$@") || { usage; exit 1; }

eval set -- "$OPTS"

while true; do
  case "$1" in
    --threads) THREADS="$2"; shift 2 ;;
    --policy) POLICY="$2"; shift 2 ;;
    --duration) DURATION="$2"; shift 2 ;;
    --rate) RATE="$2"; shift 2 ;;
    --get-frac) GET_FRAC="$2"; shift 2 ;;
    --scan-limit) SCAN_LIMIT="$2"; shift 2 ;;
    --listen) LISTEN="$2"; shift 2 ;;
    --get-delay) GET_DELAY="$2"; shift 2 ;;
    --scan-delay) SCAN_DELAY="$2"; shift 2 ;;
    --send-workers) SEND_WORKERS="$2"; shift 2 ;;
    --iterations) ITERATIONS="$2"; shift 2 ;;
    --output-dir) OUTPUT_ROOT="$2"; shift 2 ;;
    --run-id) RUN_ID_OVERRIDE="$2"; shift 2 ;;
    --state-dir) RUN_STATE_DIR_OVERRIDE="$2"; shift 2 ;;
    --server-cores) SERVER_CORES="$2"; shift 2 ;;
    --client-cores) CLIENT_CORES="$2"; shift 2 ;;
    --help) usage; exit 0 ;;
    --) shift; break ;;
    *) usage; exit 1 ;;
  esac
done

RUN_ID="${RUN_ID_OVERRIDE:-run-$(date +%Y%m%d-%H%M%S)}"
RUN_DIR="$OUTPUT_ROOT/$RUN_ID"
LOG_DIR="$RUN_DIR/logs"
STATE_DIR="${RUN_STATE_DIR_OVERRIDE:-$RUN_DIR/runstate}"
mkdir -p "$LOG_DIR" "$STATE_DIR"
export RUN_STATE_DIR="$STATE_DIR"

resolve_cpu_pool "$CPUSET_POOL"

DEFAULTED_SERVER=0
DEFAULTED_CLIENT=0

if [[ -z "$SERVER_CORES" ]]; then
  ensure_positive_int "--threads" "$THREADS"
  SERVER_CORES="$THREADS"
  DEFAULTED_SERVER=1
fi

if [[ -z "$CLIENT_CORES" ]]; then
  ensure_positive_int "--send-workers" "$SEND_WORKERS"
  CLIENT_CORES="$SEND_WORKERS"
  DEFAULTED_CLIENT=1
fi

ensure_positive_int "--server-cores" "$SERVER_CORES"
ensure_positive_int "--client-cores" "$CLIENT_CORES"
SERVER_CORES=$((SERVER_CORES))
CLIENT_CORES=$((CLIENT_CORES))

total_requested=$((SERVER_CORES + CLIENT_CORES))
if (( total_requested > ${#AVAILABLE_CPUS[@]} )); then
  echo "Insufficient NUMA node 0 CPUs: requested ${total_requested}, available ${#AVAILABLE_CPUS[@]} (${AVAILABLE_CPUS[*]})." >&2
  exit 1
fi

SERVER_CPUSET_LIST=("${AVAILABLE_CPUS[@]:0:SERVER_CORES}")
CLIENT_CPUSET_LIST=("${AVAILABLE_CPUS[@]:SERVER_CORES:CLIENT_CORES}")
SERVER_CPUSET=$(join_by , "${SERVER_CPUSET_LIST[@]}")
CLIENT_CPUSET=$(join_by , "${CLIENT_CPUSET_LIST[@]}")

if (( DEFAULTED_SERVER )); then
  echo "Server cores not supplied; defaulting to --threads value ($SERVER_CORES)"
fi
if (( DEFAULTED_CLIENT )); then
  echo "Client cores not supplied; defaulting to --send-workers value ($CLIENT_CORES)"
fi

ensure_taskset_available
export SERVER_CPUSET
export TASKSET_BIN

echo "== CPU pinning =="
echo "Server cores: $SERVER_CORES (cpuset: $SERVER_CPUSET)"
echo "Client cores: $CLIENT_CORES (cpuset: $CLIENT_CPUSET)"

BPF_PIN_BASE=${BPF_PIN_BASE:-/sys/fs/bpf/pebble}
BPF_PIN_PATH=${BPF_PIN_PATH:-$BPF_PIN_BASE/$RUN_ID}
export BPF_PIN_BASE BPF_PIN_PATH
mkdir -p "$BPF_PIN_PATH"

WORKLOAD_BIN="${WORKLOAD_BIN:-$ROOT/bin/workload_client}"

echo "== Building eBPF assets =="
SKIP_EBPF_BUILD="${SKIP_EBPF_BUILD:-false}" "$ROOT/scripts/build_ebpf.sh"

echo "== Cleaning pinned eBPF maps =="
"$ROOT/scripts/cleanup_ebpf_maps.sh"

SERVER_LOG_DIR="$LOG_DIR/server"
CLIENT_LOG_FILE="$LOG_DIR/client.log"
mkdir -p "$SERVER_LOG_DIR"
EFFECTIVE_GET_DELAY=${GET_DELAY:-10us}
EFFECTIVE_SCAN_DELAY=${SCAN_DELAY:-2ms}

if [[ -x "$WORKLOAD_BIN" ]]; then
  CLIENT_BASE_CMD=("$WORKLOAD_BIN")
else
  CLIENT_BASE_CMD=("go" "run" "./cmd/workload_client")
fi

run_client() {
  local args=("$@")
  local cmd=()
  if [[ -n "$CLIENT_CPUSET" ]]; then
    cmd+=("$TASKSET_BIN" "-c" "$CLIENT_CPUSET")
  fi
  cmd+=("${CLIENT_BASE_CMD[@]}")
  cmd+=("${args[@]}")
  "${cmd[@]}"
}

cat <<META > "$RUN_DIR/experiment.json"
{
  "threads": "$THREADS",
  "policy": "$POLICY",
  "duration_sec": "$DURATION",
  "rate_rps": "$RATE",
  "get_fraction": "$GET_FRAC",
  "scan_limit": "$SCAN_LIMIT",
  "listen": "$LISTEN",
  "get_delay": "$EFFECTIVE_GET_DELAY",
  "scan_delay": "$EFFECTIVE_SCAN_DELAY",
  "iterations": "$ITERATIONS",
  "server_cores": "$SERVER_CORES",
  "client_cores": "$CLIENT_CORES",
  "server_cpuset": "$SERVER_CPUSET",
  "client_cpuset": "$CLIENT_CPUSET"
}
META

echo "== Starting server =="
LAUNCH_ARGS=(
  -t "$THREADS"
  -p "$POLICY"
  -l "$LISTEN"
  -o "$SERVER_LOG_DIR"
  -r "$RUN_DIR"
)
if [[ -n "$GET_DELAY" ]]; then
  LAUNCH_ARGS+=(-g "$GET_DELAY")
fi
if [[ -n "$SCAN_DELAY" ]]; then
  LAUNCH_ARGS+=(-s "$SCAN_DELAY")
fi
PID_FILE="$STATE_DIR/server.pid"
SERVER_PID=""

start_server() {
  "$ROOT/scripts/launch_server.sh" "${LAUNCH_ARGS[@]}" >/dev/null
  SERVER_PID=$(cat "$PID_FILE")
  sleep 2
}

stop_server() {
  if [[ -f "$PID_FILE" ]]; then
    local pid
    pid=$(cat "$PID_FILE")
    if kill -0 "$pid" >/dev/null 2>&1; then
      kill "$pid" >/dev/null 2>&1 || true
      wait "$pid" 2>/dev/null || true
    fi
  elif [[ -n "${SERVER_PID:-}" ]]; then
    if kill -0 "$SERVER_PID" >/dev/null 2>&1; then
      kill "$SERVER_PID" >/dev/null 2>&1 || true
      wait "$SERVER_PID" 2>/dev/null || true
    fi
  fi
  rm -f "$PID_FILE"
  SERVER_PID=""
}

start_server

echo "pprof available at http://127.0.0.1:6060/debug/pprof/"
echo "block/mutex profiling enabled (SetBlockProfileRate=1)"

if [[ "$WARMUP_DURATION" =~ ^[0-9]+$ ]] && (( WARMUP_DURATION > 0 )); then
  echo "== Warmup (${WARMUP_DURATION}s) =="
  pushd "$ROOT" >/dev/null
  run_client \
    -server "$LISTEN" \
    -duration "${WARMUP_DURATION}s" \
    -rate "$RATE" \
    -get-frac "$GET_FRAC" \
    -scan-limit "$SCAN_LIMIT" \
    -send-workers "$SEND_WORKERS" \
    -log /dev/null >/dev/null 2>&1 || true
  popd >/dev/null
fi

stop_server

WORKLOAD_SUMMARY="$LOG_DIR/workload_summary.txt"
> "$WORKLOAD_SUMMARY"

echo "== Running workload iterations ($ITERATIONS) =="
pushd "$ROOT" >/dev/null
ITERATION_LOGS=()
for ((i = 1; i <= ITERATIONS; i++)); do
  ITER_LOG="$LOG_DIR/workload_iteration_${i}.txt"
  ITERATION_LOGS+=("$ITER_LOG")
  echo "-- Iteration $i/$ITERATIONS --"
  echo "Restarting server for iteration $i"
  start_server
  run_client \
    -server "$LISTEN" \
    -duration "${DURATION}s" \
    -rate "$RATE" \
    -get-frac "$GET_FRAC" \
    -scan-limit "$SCAN_LIMIT" \
    -send-workers "$SEND_WORKERS" \
    -log "$CLIENT_LOG_FILE" | tee "$ITER_LOG"
  stop_server
done
popd >/dev/null

for idx in "${!ITERATION_LOGS[@]}"; do
  iter=$((idx + 1))
  {
    echo "== Iteration $iter =="
    cat "${ITERATION_LOGS[$idx]}"
    echo
  } >> "$WORKLOAD_SUMMARY"
done

echo "== Aggregating workload metrics =="
LOG_DIR_PATH="$LOG_DIR" RUN_DIR_PATH="$RUN_DIR" python3 - <<'PY'
import json
import os
import pathlib
import re
import statistics

log_dir = pathlib.Path(os.environ["LOG_DIR_PATH"])
iter_files = sorted(log_dir.glob("workload_iteration_*.txt"))
if not iter_files:
    raise SystemExit("no workload iteration logs found")

total_sent_re = re.compile(r"Total sent:\s+(\d+)\s+\(GET=(\d+)\s+SCAN=(\d+)\)")
total_recv_re = re.compile(r"Total received:\s+(\d+)\s+\(GET=(\d+)\s+SCAN=(\d+)\)")
throughput_re = re.compile(r"Throughput:\s+([0-9.]+)\s+req/s")
latency_re = re.compile(r"^(Overall|GET|SCAN) latency (p50|p90|p99|avg):\s+([0-9.]+)\s+ms")

def parse_file(path, iteration):
    metrics = {"iteration": iteration}
    with path.open() as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue
            m = total_sent_re.match(line)
            if m:
                metrics["total_sent"] = int(m.group(1))
                metrics["total_sent_get"] = int(m.group(2))
                metrics["total_sent_scan"] = int(m.group(3))
                continue
            m = total_recv_re.match(line)
            if m:
                metrics["total_received"] = int(m.group(1))
                metrics["total_received_get"] = int(m.group(2))
                metrics["total_received_scan"] = int(m.group(3))
                continue
            m = throughput_re.match(line)
            if m:
                metrics["throughput"] = float(m.group(1))
                continue
            m = latency_re.match(line)
            if m:
                scope = m.group(1).lower()
                stat = m.group(2).lower()
                key = f"{scope}_latency_{stat}"
                metrics[key] = float(m.group(3))
                continue
    return metrics

iterations = []
for idx, path in enumerate(iter_files, start=1):
    iterations.append(parse_file(path, idx))

summary = {}
numeric_keys = sorted({k for entry in iterations for k in entry.keys() if k != "iteration"})
for key in numeric_keys:
    values = [entry[key] for entry in iterations if isinstance(entry.get(key), (int, float))]
    if not values:
        continue
    avg = statistics.mean(values)
    stddev = statistics.pstdev(values) if len(values) > 1 else 0.0
    summary[key] = {"average": avg, "stddev": stddev}

output = {"iterations": iterations, "summary": summary}
results_dir = pathlib.Path(os.environ["RUN_DIR_PATH"])
(results_dir / "workload_summary.json").write_text(json.dumps(output, indent=2))
PY

echo "== Stopping server =="
stop_server
if [[ -n "${BPF_PIN_PATH:-}" ]]; then
  rm -rf "$BPF_PIN_PATH" 2>/dev/null || true
fi

echo "Logs and results stored in $RUN_DIR"
