//go:build ignore

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

struct {
    __uint(type, BPF_MAP_TYPE_REUSEPORT_SOCKARRAY);
    __uint(max_entries, 128);
    __type(key, __u32);
    __type(value, __u32);
    __uint(pinning, LIBBPF_PIN_BY_NAME);
} pebble_udp_targets SEC(".maps");

// EVOLVE-BLOCK-START

/*
 * Design:
 * -------
 * Previous versions of this selector focused on spreading traffic evenly
 * across workers (e.g., via per-packet randomness). That flattens per‑worker
 * utilization but still mixes short GETs (~10 µs) and long SCANs (~2 ms) on
 * every UDP receive queue. Even with balanced CPU, rare SCANs create
 * head-of-line blocking for many queued GETs on a given worker, which shows
 * up as high end-to-end p99 latency at high load.
 *
 * Goals:
 *   - Minimize the time GETs spend queued behind SCANs.
 *   - Keep all workers usefully busy without new maps or user-space config.
 *   - Stay verifier-friendly: O(1) per packet, no loops, minimal state.
 *
 * Approach: static GET / SCAN lane partitioning.
 * ----------------------------------------------
 * We use the existing pebble_agent_state map (Active workers) and treat the
 * reuseport sockarray indices as two static "lanes":
 *
 *   - SCAN lane:   index 0 (one worker dedicated to SCANs when Active > 1).
 *   - GET lane:    indices [1, Active-1] (all remaining workers).
 *
 * When there is only a single worker (Active == 1), the lanes collapse and
 * we simply select slot 0.
 *
 * For each packet:
 *   1. Safely parse the incoming IPv4/UDP headers from sk_reuseport_md::data
 *      and locate the UDP payload.
 *   2. Inspect the first few payload bytes to classify the request:
 *        - "SCAN " → SCAN request.
 *        - Everything else (including "GET ...") → treated as GET/other.
 *   3. Choose a lane:
 *        - SCANs → SCAN lane (slot range [0, 0] when Active > 1).
 *        - GET/other → GET lane (slot range [1, Active-1] when Active > 1).
 *   4. Within the chosen lane, pick a worker index using
 *      bpf_get_prandom_u32() % lane_size.
 *   5. Call bpf_sk_select_reuseport once with that slot.
 *
 * This ensures that long SCAN requests are funneled into a small, fixed
 * subset of workers and do not share UDP queues with GETs. GETs are thus
 * processed on workers that rarely, if ever, run SCANs, substantially
 * reducing their queueing delay and improving overall p99 latency.
 *
 * The program remains:
 *   - Stateless per packet (no per-flow state, no counters).
 *   - O(1) in work and memory.
 *   - Within verifier limits (no loops, all pointer accesses bounds-checked).
 */

struct agent_state {
    __u32 active;
    __u32 pad;
};

struct {
    __uint(type, BPF_MAP_TYPE_ARRAY);
    __uint(max_entries, 1);
    __type(key, __u32);
    __type(value, struct agent_state);
    __uint(pinning, LIBBPF_PIN_BY_NAME);
} pebble_agent_state SEC(".maps");

SEC("sk_reuseport/selector")
enum sk_action agent_udp_selector(struct sk_reuseport_md *reuse)
{
    __u32 key = 0;
    struct agent_state *state = bpf_map_lookup_elem(&pebble_agent_state, &key);
    if (!state)
        return SK_PASS;

    __u32 active = state->active;
    if (active == 0)
        return SK_PASS;

    /* Safety: never index beyond the sockarray size even if misconfigured. */
    if (active > 128)
        active = 128;

    /*
     * Classify packet as SCAN vs non-SCAN by peeking into the UDP payload.
     * We assume IPv4+UDP as generated by the workload client. All accesses
     * are guarded by data_end checks so the verifier can prove safety.
     */
    int is_scan = 0;

    void *data = (void *)(long)reuse->data;
    void *data_end = (void *)(long)reuse->data_end;

    /* Need at least 10 bytes of IPv4 header to read version/IHL and protocol. */
    if ((void *)((__u8 *)data + 10) > data_end)
        goto classify_done;

    __u8 ver_ihl = ((__u8 *)data)[0];
    __u8 version = ver_ihl >> 4;
    __u8 ihl     = ver_ihl & 0x0F;

    /* Only handle IPv4; anything else falls back to non-SCAN. */
    if (version != 4)
        goto classify_done;

    /* IHL is in 32-bit words; valid range for IPv4 header is [5, 15]. */
    if (ihl < 5 || ihl > 15)
        goto classify_done;

    __u32 ip_header_len = (__u32)ihl * 4;

    /* Ensure the full IPv4 header and UDP header (8 bytes) are present. */
    if ((void *)((__u8 *)data + ip_header_len + 8) > data_end)
        goto classify_done;

    /* Protocol field is at offset 9 of the IPv4 header. */
    __u8 proto = ((__u8 *)data)[9];
    /* 17 == IPPROTO_UDP */
    if (proto != 17)
        goto classify_done;

    /* UDP payload starts after the variable-length IPv4 header and 8-byte UDP header. */
    {
        __u8 *udp_payload = (__u8 *)data + ip_header_len + 8;

        /* We need at least 1 byte to check for leading 'S'. */
        if ((void *)(udp_payload + 1) > data_end)
            goto classify_done;

        if (udp_payload[0] == 'S') {
            /* We need full "SCAN " / "SCAN\t" (5 bytes) to classify as SCAN. */
            if ((void *)(udp_payload + 5) <= data_end &&
                udp_payload[1] == 'C' &&
                udp_payload[2] == 'A' &&
                udp_payload[3] == 'N' &&
                (udp_payload[4] == ' ' || udp_payload[4] == '\t')) {
                is_scan = 1;
            }
        }
    }

classify_done:
    /*
     * Lane selection:
     *  - If only one worker is active, everyone goes to slot 0.
     *  - If more than one worker:
     *      - SCANs  → slot 0 (SCAN lane, size 1).
     *      - others → slots [1, active-1] (GET lane).
     */
    __u32 lane_start = 0;
    __u32 lane_size  = active;

    if (active > 1) {
        __u32 scan_cnt = 1;
        __u32 get_cnt  = active - scan_cnt;

        if (is_scan) {
            lane_start = 0;
            lane_size  = scan_cnt;  /* == 1 */
        } else {
            lane_start = scan_cnt;  /* == 1 */
            lane_size  = get_cnt;   /* >= 1 */
        }
    }

    if (lane_size == 0)
        return SK_PASS;

    __u32 rnd = bpf_get_prandom_u32();
    __u32 idx = rnd % lane_size;
    __u32 slot = lane_start + idx;

    /* Single reuseport selection; kernel ignores any additional calls. */
    bpf_sk_select_reuseport(reuse, &pebble_udp_targets, &slot, 0);

    return SK_PASS;
}

// EVOLVE-BLOCK-END

char _license[] SEC("license") = "GPL";